---
- name: install pyenv-virtualenv
  yum: name={{ item }} state=present 
  with_items:
   - https://centos7.iuscommunity.org/ius-release.rpm
   - zlib
   - tk-devel
   - tcl-devel
   - ncurses-devel
   - gdbm-devel
   - db4-devel
   - readline-devel
   - zlib-devel
   - bzip2-devel
   - sqlite-devel
   - openssl-devel
   - libXext.x86_64
   - libSM.x86_64
   - libXrender.x86_64
   - gcc
   - gcc-c++
   - libffi-devel
   - python-devel
   - patch
   - bzip2
   - readline
   - sqlite
   - git
   - epel-release
   - python-pip
   - python36u
   - python36u-devel
   - python36u-libs
   - python36u-pip

     



