---
- name: install repo
  yum: name=https://centos7.iuscommunity.org/ius-release.rpm

- name: install pyenv-virtualenv
  yum: name={{ item }} state=present 
  with_items:
    - zlib
    - tk-devel
    - tcl-devel
    - ncurses-devel
    - gdbm-devel
    - db4-devel
    - readline-devel
    - zlib-devel
    - bzip2-devel
    - sqlite-devel
    - openssl-devel
    - libXext.x86_64
    - libSM.x86_64
    - libXrender.x86_64
    - gcc
    - gcc-c++
    - libffi-devel
    - python-devel
    - patch
    - bzip2
    - readline
    - sqlite
    - git
    - epel-release
    - python-pip
    - python36u
    - python36u-devel
    - python36u-libs
    - python36u-pip

- name: create Symbolic link
  file:
    src: /usr/bin/python3.6
    dest: /usr/bin/python3
    state: link


- name: upgrade pip
  shell: bash -lc "pip3.6 install --upgrade pip"
#  pip:
#    name: pip
#    executable: pip3
#    state: latest


- name: install virtualenv 
  pip:
    name:  
      - setuptools
      - virtualenv
    state: latest


- name: change bashrc
  blockinfile:
    dest: /root/.bashrc
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"

- shell: bash -lc "source ~/.bashrc"

- shell: bash -lc "virtualenv ansible"


# - shell: bash -lc "source ./bin/activate"
#  args:
#    chdir: ~/ansible/


- name: install pip ansible
  pip:
    name: ansible
    virtualenv: ~/ansible/
    virtualenv_python: python3.6
    state: latest
  args:
    chdir: ~/ansible

# - shell: bash -lc "deactivate"


